title: "Sonu Kapoor"
description: "Google Developer Expert (Angular) · 7x Microsoft MVP · Author · Open-Source Leader"
url: "https://sonukapoor.com"
baseurl: ""
permalink: /:collection/:name/
markdown: kramdown

# GitHub Pages-safe theme & plugins
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope: { path: "", type: "awards" }
    values: { layout: detail }
  - scope: { path: "", type: "books" }
    values: { layout: detail }
  - scope: { path: "", type: "media" }
    values: { layout: detail }
  - scope: { path: "", type: "articles" }
    values: { layout: detail }
  - scope: { path: "", type: "podcasts" }
    values: { layout: detail }
  - scope: { path: "", type: "contributions" }
    values: { layout: detail }
